name: Local CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Minikube Docker
        run: eval $(minikube docker-env)

      - name: Build Docker image
        run: docker build -t flask-todo:latest .

      - name: Apply Deployment
        run: |
          kubectl apply -f k8s/deployment.yml
          kubectl rollout status deployment flask-todo-deployment

      - name: Apply Service
        run: kubectl apply -f k8s/service.yml
