name: CI Pipeline

on:
  push:         # Run pipeline when code is pushed
    branches: [ main ]
  pull_request: # Run pipeline when a PR is opened
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest   # GitHub gives us a Linux VM

    steps:
      # Step 1: Checkout code from GitHub
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Step 4: Run tests
      - name: Run Tests
        run: |
          export PYTHONPATH=$(pwd)
          pytest tests/

      - name: List files
        run: ls -R

